theme: jekyll-theme-leap-day
plugins:
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-avatar
   - jekyll-mentions
     #   - jekyll-include-cache
