theme: jekyll-theme-leap-day
title: The title of your site
description: A short description of your site's purpose
show_downloads: false

plugins:
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-avatar
   - jekyll-mentions
     #   - jekyll-include-cache
