theme: jekyll-theme-leap-day
title: felix's blog
description: This blog is about my experiences in software development, I hope you can find something useful!
show_downloads: false
permalink: /:categories/:title/
excerpt_separator: <!--more-->
paginate: 10

plugins:
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-avatar
   - jekyll-mentions
   - jekyll-timeago
     #   - jekyll-include-cache
